name: master-branch-build

on:
  push:
    branches: master

jobs:
  build:
    env:
      MAIN_PRE_RELEASE_TAG: beta
      MAIN_ZIP_NAME: MSFS-Pushback-Helper-App-beta.zip
    runs-on: [windows-latest]

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Build
      run: msbuild PushbackHelper.sln -t:restore -p:RestorePackagesConfig=true /p:Configuration=Release /p:Platform=x64
    - name: Create ZIP file
      shell: bash
      run: |
        7z a -tzip "./${{ env.MAIN_ZIP_NAME }}" "./PushbackHelper/bin/Release/*"
    - name: Upload release asset
      id: upload-release-asset 
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./${{ env.MAIN_ZIP_NAME }}
        asset_name: ${{ env.MAIN_ZIP_NAME }}
        tag: ${{ env.MAIN_PRE_RELEASE_TAG }}
        overwrite: true
        body: "This pre-release has its ${{ env.MAIN_ZIP_NAME }} asset updated on every commit to the main branch\nDo not use the source code assets, they are never updated\nLast updated from commit ${{ github.sha }}\nThis link will always point to the latest main build: https://github.com/${{ github.repository }}/releases/download/${{ env.MAIN_PRE_RELEASE_TAG }}/${{ env.MAIN_ZIP_NAME }}"
